### PR TITLE
Fix syntax error in commit f29d49d47

### PR DESCRIPTION
**Pull request by jwodder**

### CODE REVIEW

**Comment by jwodder** [comment]
Manually-triggered builds:
* Ubuntu: https://github.com/datalad/git-annex/actions/runs/425780839
* macOS: https://github.com/datalad/git-annex/actions/runs/425780837
* Windows: https://github.com/datalad/git-annex/actions/runs/425780840

**Comment by yarikoptic** [comment]
cool, send to @joeyh ?

**Comment by jwodder** [comment]
Reported: https://git-annex.branchable.com/bugs/Syntax_error_in_comit_f29d49d47/

**Comment by yarikoptic** [comment]
probably no need to keep this PR open, we will just wait for it to be fixed upstream soonish, and if not -- add a patch within `master`

**Comment by yarikoptic** [comment]
I was silly -- it was within master, so let's merge!

**Pull request merged**
