### PR TITLE
Fix compilation errors on Windows in commit a706708d1

### PR DESCRIPTION
**Pull request by jwodder**

### CODE REVIEW

**Comment by yarikoptic** [comment]
Thanks !  Was sent to @joeyh as well?

**Comment by jwodder** [comment]
@yarikoptic Not yet; I'm waiting for the CI to finish to make sure there aren't any related errors.

**Comment by jwodder** [comment]
Reported: https://git-annex.branchable.com/bugs/Build_fails_on_Windows_as_of_commit_a706708d1/

**Comment by yarikoptic** [comment]
Great, thank you @jwodder

**Pull request merged**
