### PR TITLE
Run macOS build on 10.15

### LINKED ISSUE #95: OSX build fails
https://github.com/datalad/git-annex/runs/4465340747?check_suite_focus=true

```
[24 of 24] Compiling Main             ( Build/Standalone.hs, Build/Standalone.o )
Linking Build/Standalone ...
./Build/Standalone tmp/build-dmg/git-annex.app/Contents/MacOS/bundle tmp/build-dmg/git-annex.app
cp: /usr/lib/libiconv.2.dylib: No such file or directory
installing /usr/local/opt/pcre2/lib/libpcre2-8.0.dylib as A
Standalone: library install failed
CallStack (from HasCallStack):
  error, called at ./Build/OSXMkLibs.hs:73:41 in main:Build.OSXMkLibs
installing /usr/lib/libiconv.2.dylib as B
make: *** [osxapp] Error 1
```
attn @joeyh @jwodder (since I don't know if that is env issue or annex code issue)

### PR DESCRIPTION
**Pull request by jwodder**
Fixes #95 (hopefully).

### CODE REVIEW

**Comment by yarikoptic** [comment]
woohoo - `build-package` seems to pass, so it is promising!

**Comment by jwodder** [comment]
@yarikoptic Test spec compressed.

**Comment by yarikoptic** [comment]
fancy cool! Thank you @jwodder ! Let's proceed!

Do you remember if we have a way to trigger rebuild/upload of extra artifact to an existing release?  the 20211231 one is missing OSX build.

**Comment by jwodder** [comment]
@yarikoptic I manually triggered a build of the tag for macOS, thereby causing the build artifact to be added to the release.

**Pull request merged**
