### PR TITLE
Copy workflows from datalad-extensions (resubmission)

### PR DESCRIPTION
**Pull request by jwodder**
Addresses datalad/datalad-extensions#67.

Resubmitting #5 because the force-push to master made GitHub close the original PR.

TODO:
- [x] Update for the change in branch setup

### CODE REVIEW

**Comment by jwodder** [comment]
@yarikoptic The workflow handles the multi-branch setup fine now.  The only issue is that the Ubuntu build is failing because of some problem applying a patch that I know nothing about.

**Comment by yarikoptic** [comment]
patch is ok, it is the earlier rule in the makefile which fails:
```
fatal: No tags can describe '6ea79180e2387c55b038a6b585c52a253f2654e7'.
Try --always, or create some tags.
make: *** [Makefile:194: prep-standalone] Error 128
```
because we build out of that git branch.  Pushed 83e97333615eda9fc4846d713b3087dc6a9e9ef9 which should help

BTW -- I guess for "pull requests" we should limit workflows to only react when the workflow changes (now rebuilds for all) or  you think that would affect our ability later to provide builds of git-annex (which we would be triggering "manually" anyways)?

**Comment by jwodder** [comment]
> BTW -- I guess for "pull requests" we should limit workflows to only react when the workflow changes (now rebuilds for all) or you think that would affect our ability later to provide builds of git-annex (which we would be triggering "manually" anyways)?

I'm not entirely clear on what you're suggesting.  The "`on`" section for each workflow is already of the form:

```
on:
   # Trigger the workflow on pull request,
   pull_request:
     paths:
       - '.github/workflows/build-macos.yaml'
   schedule:
     - cron: '30 01 * * *'
```

This should ensure that the workflows only run when changed in a pull request (and also on a schedule).  I believe the reason they're all being rebuilt on a commit that touches only one of them is because the PR as a whole changes all of them.  I don't think there's a way to change that behavior.

**Comment by yarikoptic** [comment]
oh, indeed... I just assumed that they were absent since it rebuilt.

Anyways -- git-annex FTBFS ATM across the board, I hope @joeyh would just fix it up soon so we will just try later again

**Comment by yarikoptic** [comment]
restarted builds, linux seems to build now, but fails the tests. restarted osx and windows.  Let's see where they stand

**Comment by yarikoptic** [comment]
@jwodder Could you please add to "Get build version" actually showing that version which is built? if build fails it seems it is nowhere to be found .  
Current state -- both Windows and OSX are still failing 

Windows 
```
[17 of 29] Compiling Utility.Path     ( Utility\Path.hs, D:\\a\git-annex\git-annex\.stack-work\dist\29cc6475\setup\Utility\Path.o )

Utility\Path.hs:224:25: error:
    Variable not in scope: toLower :: Char -> b
    |
224 |         normdrive = map toLower . takeWhile (/= ':') . fromRawFilePath . takeDrive

    |                         ^^^^^^^

--  While building package git-annex-8.20201103 using:
      C:\Users\runneradmin\AppData\Local\Programs\stack\x86_64-windows\ghc-8.8.4\bin\ghc-8.8.4.EXE --make -odir D:\a\git-annex\git-annex\.stack-work\dist\29cc6475\setup -hidir D:\a\git-annex\git-annex\.stack-work\dist\29cc6475\setup -i -i. -clear-package-db -global-package-db -package-db=C:\sr\snapshots\803735b3\pkgdb -package-db=D:\a\git-annex\git-annex\.stack-work\install\2da37c3b\pkgdb -hide-all-packages -package-id=Cabal-3.0.1.0 -package-id=IfElse-0.85-8XBRQf5oZUNFDlR7r8dCe3 -package-id=async-2.2.2-KJKVlh0cMBrJuriUQALiHZ -package-id=base-4.13.0.0 -package-id=bytestring-0.10.10.1 -package-id=data-default-0.7.1.1-5cjrhz8y8DG881Qqkxq9GB -package-id=directory-1.3.6.0 -package-id=exceptions-0.10.4-6ENJVzINLe28VlhOUrvEZK -package-id=filepath-1.4.2.1 -package-id=filepath-bytestring-1.4.2.1.6-rts4ei4gMKHl4oJSIPi7X -package-id=hslogger-1.3.1.0-BA4fFKRgZKz1iO1ML6Bujq -package-id=process-1.6.9.0 -package-id=split-0.2.3.4-KyPtAwfJzED2zEIheQpqQL -package-id=transformers-0.5.6.2 -package-id=unix-compat-0.5.2-1GXUtTiqbs7JOaJgVDICSY -package-id=utf8-string-1.0.1.1-K3Cc2i5eeGM49mkpXdBKoc -optP-include -optPD:\a\git-annex\git-annex\.stack-work\dist\29cc6475\setup\setup_macros.h D:\a\git-annex\git-annex\Setup.hs C:\sr\setup-exe-src\setup-shim-Z6RU0evB.hs -main-is StackSetupShim.mainOverride -o D:\a\git-annex\git-annex\.stack-work\dist\29cc6475\setup\setup -threaded
    Process exited with code: ExitFailure 1
```
OSX:
```
2020-11-09T21:46:24.2383260Z Assistant/Install/AutoStart.hs:23:40: error:
2020-11-09T21:46:24.2385230Z     • Couldn't match type ‘Data.ByteString.Internal.ByteString’
2020-11-09T21:46:24.2386210Z                      with ‘[Char]’
2020-11-09T21:46:24.2386520Z       Expected type: FilePath
2020-11-09T21:46:24.2387610Z         Actual type: unix-2.7.2.2:System.Posix.ByteString.FilePath.RawFilePath
2020-11-09T21:46:24.2388930Z     • In the second argument of ‘createDirectoryIfMissing’, namely
2020-11-09T21:46:24.2389720Z         ‘(parentDir file)’
2020-11-09T21:46:24.2390370Z       In a stmt of a 'do' block:
2020-11-09T21:46:24.2390870Z         createDirectoryIfMissing True (parentDir file)
2020-11-09T21:46:24.2391330Z       In the expression:
2020-11-09T21:46:24.2391770Z         do createDirectoryIfMissing True (parentDir file)
2020-11-09T21:46:24.2392220Z            writeFile file
2020-11-09T21:46:24.2392570Z              $ genOSXAutoStartFile
2020-11-09T21:46:24.2393430Z                  osxAutoStartLabel command ["assistant", "--autostart"]
2020-11-09T21:46:24.2393810Z    |
2020-11-09T21:46:24.2394210Z 23 |         createDirectoryIfMissing True (parentDir file)
2020-11-09T21:46:24.2394620Z    |                                        ^^^^^^^^^^^^^^
2020-11-09T21:46:24.2394770Z 
2020-11-09T21:46:24.2395080Z Assistant/Install/AutoStart.hs:23:50: error:
2020-11-09T21:46:24.2395820Z     • Couldn't match type ‘[Char]’
2020-11-09T21:46:24.2396720Z                      with ‘Data.ByteString.Internal.ByteString’
2020-11-09T21:46:24.2398050Z       Expected type: unix-2.7.2.2:System.Posix.ByteString.FilePath.RawFilePath
2020-11-09T21:46:24.2399180Z         Actual type: FilePath
2020-11-09T21:46:24.2399920Z     • In the first argument of ‘parentDir’, namely ‘file’
2020-11-09T21:46:24.2400830Z       In the second argument of ‘createDirectoryIfMissing’, namely
2020-11-09T21:46:24.2401640Z         ‘(parentDir file)’
2020-11-09T21:46:24.2402260Z       In a stmt of a 'do' block:
2020-11-09T21:46:24.2402720Z         createDirectoryIfMissing True (parentDir file)
2020-11-09T21:46:24.2403120Z    |
2020-11-09T21:46:24.2403520Z 23 |         createDirectoryIfMissing True (parentDir file)
2020-11-09T21:46:24.2403990Z    |                                                  ^^^^
2020-11-09T21:46:24.3049490Z Completed 205 action(s).
2020-11-09T21:46:24.3062900Z 
```

**Comment by jwodder** [comment]
@yarikoptic Done.

**Comment by yarikoptic** [comment]
ok, Linux is in clear, mac and OSX might not yet ... anyways -- let's proceed since re-running those here is not fun, and we better just rely on cron job to eventually to succeed or we will look into what we need to fix up later on our end

**Pull request merged**
