### PR TITLE
Use docker-practice/actions-setup-docker to set up Docker on macOS

### PR DESCRIPTION
**Pull request by jwodder**
This is an alternative to #55.

### CODE REVIEW

**Comment by yarikoptic** [comment]
it somehow wasn't in effect? I still see `/Users/runner/DLTMP` ... needs debugging. BTW -- does it replicate on your OSX laptop (trying to ssh into that docker container etc)?

**Comment by jwodder** [comment]
@yarikoptic I forgot to run `make` after updating the template for the previous commit.  That's fixed now.

**Comment by yarikoptic** [comment]
now it is red across all CI runs for test-datalad, I guess more work todo

**Comment by jwodder** [comment]
@yarikoptic Datalad seems to be resolving `TMPDIR` on the host machine and then using that path inside the Docker container, which leads to failures, as `/tmp` on macOS is a symlink to `/private/tmp`, which doesn't exist inside the containers and which Datalad doesn't have permission to create.

**Comment by yarikoptic** [comment]
re ubuntu fails -- would be worth rerunning, I think the issue with `test_expanduser` failing was identified/resolved.

re OSX: I guess we should bind mount resolved `/tmp` (`/private/tmp`?) as well to resolve it?

**Comment by jwodder** [comment]
Closing as the action in question does not seem to work properly any more.

**Pull request closed without merging**
